/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PoliticaDeEnvioRouteImport } from './routes/politica-de-envio'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeReembolsoRouteImport } from './routes/politica-de-reembolso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCartoesRouteImport } from './routes/admin.cartoes'
import { Route as AdminComprovantesRouteImport } from './routes/admin.comprovantes'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminGatewaysRouteImport } from './routes/admin.gateways'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminRastreioRouteImport } from './routes/admin.rastreio'
import { Route as AdminTiktokRouteImport } from './routes/admin.tiktok'
import { Route as AdminTrafegoRouteImport } from './routes/admin.trafego'
import { Route as CheckoutDadosRouteImport } from './routes/checkout.dados'
import { Route as CheckoutGarantiaRouteImport } from './routes/checkout.garantia'
import { Route as CheckoutPixRouteImport } from './routes/checkout.pix'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutUpsellRouteImport } from './routes/checkout.upsell'
import { Route as ApiAdminStreamRouteImport } from './routes/api.admin.stream'
import { Route as ApiWebhooksAxxonpayRouteImport } from './routes/api.webhooks.axxonpay'
import { Route as ApiWebhooksBeehiveRouteImport } from './routes/api.webhooks.beehive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeEnvioRoute = PoliticaDeEnvioRouteImport.update({
  id: '/politica-de-envio',
  path: '/politica-de-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeReembolsoRoute = PoliticaDeReembolsoRouteImport.update({
  id: '/politica-de-reembolso',
  path: '/politica-de-reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCartoesRoute = AdminCartoesRouteImport.update({
  id: '/admin/cartoes',
  path: '/admin/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComprovantesRoute = AdminComprovantesRouteImport.update({
  id: '/admin/comprovantes',
  path: '/admin/comprovantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGatewaysRoute = AdminGatewaysRouteImport.update({
  id: '/admin/gateways',
  path: '/admin/gateways',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/admin/integracoes',
  path: '/admin/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRastreioRoute = AdminRastreioRouteImport.update({
  id: '/admin/rastreio',
  path: '/admin/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTiktokRoute = AdminTiktokRouteImport.update({
  id: '/admin/tiktok',
  path: '/admin/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrafegoRoute = AdminTrafegoRouteImport.update({
  id: '/admin/trafego',
  path: '/admin/trafego',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutDadosRoute = CheckoutDadosRouteImport.update({
  id: '/checkout/dados',
  path: '/checkout/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutGarantiaRoute = CheckoutGarantiaRouteImport.update({
  id: '/checkout/garantia',
  path: '/checkout/garantia',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPixRoute = CheckoutPixRouteImport.update({
  id: '/checkout/pix',
  path: '/checkout/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutUpsellRoute = CheckoutUpsellRouteImport.update({
  id: '/checkout/upsell',
  path: '/checkout/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStreamRoute = ApiAdminStreamRouteImport.update({
  id: '/api/admin/stream',
  path: '/api/admin/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksAxxonpayRoute = ApiWebhooksAxxonpayRouteImport.update({
  id: '/api/webhooks/axxonpay',
  path: '/api/webhooks/axxonpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksBeehiveRoute = ApiWebhooksBeehiveRouteImport.update({
  id: '/api/webhooks/beehive',
  path: '/api/webhooks/beehive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-de-envio': typeof PoliticaDeEnvioRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-reembolso': typeof PoliticaDeReembolsoRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/cartoes': typeof AdminCartoesRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/rastreio': typeof AdminRastreioRoute
  '/admin/tiktok': typeof AdminTiktokRoute
  '/admin/trafego': typeof AdminTrafegoRoute
  '/checkout/dados': typeof CheckoutDadosRoute
  '/checkout/garantia': typeof CheckoutGarantiaRoute
  '/checkout/pix': typeof CheckoutPixRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/checkout/upsell': typeof CheckoutUpsellRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/stream': typeof ApiAdminStreamRoute
  '/api/webhooks/axxonpay': typeof ApiWebhooksAxxonpayRoute
  '/api/webhooks/beehive': typeof ApiWebhooksBeehiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-de-envio': typeof PoliticaDeEnvioRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-reembolso': typeof PoliticaDeReembolsoRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/cartoes': typeof AdminCartoesRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/rastreio': typeof AdminRastreioRoute
  '/admin/tiktok': typeof AdminTiktokRoute
  '/admin/trafego': typeof AdminTrafegoRoute
  '/checkout/dados': typeof CheckoutDadosRoute
  '/checkout/garantia': typeof CheckoutGarantiaRoute
  '/checkout/pix': typeof CheckoutPixRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/checkout/upsell': typeof CheckoutUpsellRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/stream': typeof ApiAdminStreamRoute
  '/api/webhooks/axxonpay': typeof ApiWebhooksAxxonpayRoute
  '/api/webhooks/beehive': typeof ApiWebhooksBeehiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/politica-de-envio': typeof PoliticaDeEnvioRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-reembolso': typeof PoliticaDeReembolsoRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/cartoes': typeof AdminCartoesRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gateways': typeof AdminGatewaysRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/rastreio': typeof AdminRastreioRoute
  '/admin/tiktok': typeof AdminTiktokRoute
  '/admin/trafego': typeof AdminTrafegoRoute
  '/checkout/dados': typeof CheckoutDadosRoute
  '/checkout/garantia': typeof CheckoutGarantiaRoute
  '/checkout/pix': typeof CheckoutPixRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/checkout/upsell': typeof CheckoutUpsellRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/stream': typeof ApiAdminStreamRoute
  '/api/webhooks/axxonpay': typeof ApiWebhooksAxxonpayRoute
  '/api/webhooks/beehive': typeof ApiWebhooksBeehiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/faq'
    | '/politica-de-envio'
    | '/politica-de-privacidade'
    | '/politica-de-reembolso'
    | '/sobre'
    | '/termos-de-uso'
    | '/admin/cartoes'
    | '/admin/comprovantes'
    | '/admin/dashboard'
    | '/admin/gateways'
    | '/admin/integracoes'
    | '/admin/pedidos'
    | '/admin/rastreio'
    | '/admin/tiktok'
    | '/admin/trafego'
    | '/checkout/dados'
    | '/checkout/garantia'
    | '/checkout/pix'
    | '/checkout/sucesso'
    | '/checkout/upsell'
    | '/admin/'
    | '/api/admin/stream'
    | '/api/webhooks/axxonpay'
    | '/api/webhooks/beehive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/faq'
    | '/politica-de-envio'
    | '/politica-de-privacidade'
    | '/politica-de-reembolso'
    | '/sobre'
    | '/termos-de-uso'
    | '/admin/cartoes'
    | '/admin/comprovantes'
    | '/admin/dashboard'
    | '/admin/gateways'
    | '/admin/integracoes'
    | '/admin/pedidos'
    | '/admin/rastreio'
    | '/admin/tiktok'
    | '/admin/trafego'
    | '/checkout/dados'
    | '/checkout/garantia'
    | '/checkout/pix'
    | '/checkout/sucesso'
    | '/checkout/upsell'
    | '/admin'
    | '/api/admin/stream'
    | '/api/webhooks/axxonpay'
    | '/api/webhooks/beehive'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/faq'
    | '/politica-de-envio'
    | '/politica-de-privacidade'
    | '/politica-de-reembolso'
    | '/sobre'
    | '/termos-de-uso'
    | '/admin/cartoes'
    | '/admin/comprovantes'
    | '/admin/dashboard'
    | '/admin/gateways'
    | '/admin/integracoes'
    | '/admin/pedidos'
    | '/admin/rastreio'
    | '/admin/tiktok'
    | '/admin/trafego'
    | '/checkout/dados'
    | '/checkout/garantia'
    | '/checkout/pix'
    | '/checkout/sucesso'
    | '/checkout/upsell'
    | '/admin/'
    | '/api/admin/stream'
    | '/api/webhooks/axxonpay'
    | '/api/webhooks/beehive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  PoliticaDeEnvioRoute: typeof PoliticaDeEnvioRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeReembolsoRoute: typeof PoliticaDeReembolsoRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  AdminCartoesRoute: typeof AdminCartoesRoute
  AdminComprovantesRoute: typeof AdminComprovantesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGatewaysRoute: typeof AdminGatewaysRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminRastreioRoute: typeof AdminRastreioRoute
  AdminTiktokRoute: typeof AdminTiktokRoute
  AdminTrafegoRoute: typeof AdminTrafegoRoute
  CheckoutDadosRoute: typeof CheckoutDadosRoute
  CheckoutGarantiaRoute: typeof CheckoutGarantiaRoute
  CheckoutPixRoute: typeof CheckoutPixRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
  CheckoutUpsellRoute: typeof CheckoutUpsellRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminStreamRoute: typeof ApiAdminStreamRoute
  ApiWebhooksAxxonpayRoute: typeof ApiWebhooksAxxonpayRoute
  ApiWebhooksBeehiveRoute: typeof ApiWebhooksBeehiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-envio': {
      id: '/politica-de-envio'
      path: '/politica-de-envio'
      fullPath: '/politica-de-envio'
      preLoaderRoute: typeof PoliticaDeEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-reembolso': {
      id: '/politica-de-reembolso'
      path: '/politica-de-reembolso'
      fullPath: '/politica-de-reembolso'
      preLoaderRoute: typeof PoliticaDeReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cartoes': {
      id: '/admin/cartoes'
      path: '/admin/cartoes'
      fullPath: '/admin/cartoes'
      preLoaderRoute: typeof AdminCartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comprovantes': {
      id: '/admin/comprovantes'
      path: '/admin/comprovantes'
      fullPath: '/admin/comprovantes'
      preLoaderRoute: typeof AdminComprovantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gateways': {
      id: '/admin/gateways'
      path: '/admin/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AdminGatewaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rastreio': {
      id: '/admin/rastreio'
      path: '/admin/rastreio'
      fullPath: '/admin/rastreio'
      preLoaderRoute: typeof AdminRastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tiktok': {
      id: '/admin/tiktok'
      path: '/admin/tiktok'
      fullPath: '/admin/tiktok'
      preLoaderRoute: typeof AdminTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trafego': {
      id: '/admin/trafego'
      path: '/admin/trafego'
      fullPath: '/admin/trafego'
      preLoaderRoute: typeof AdminTrafegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/dados': {
      id: '/checkout/dados'
      path: '/checkout/dados'
      fullPath: '/checkout/dados'
      preLoaderRoute: typeof CheckoutDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/garantia': {
      id: '/checkout/garantia'
      path: '/checkout/garantia'
      fullPath: '/checkout/garantia'
      preLoaderRoute: typeof CheckoutGarantiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pix': {
      id: '/checkout/pix'
      path: '/checkout/pix'
      fullPath: '/checkout/pix'
      preLoaderRoute: typeof CheckoutPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/upsell': {
      id: '/checkout/upsell'
      path: '/checkout/upsell'
      fullPath: '/checkout/upsell'
      preLoaderRoute: typeof CheckoutUpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stream': {
      id: '/api/admin/stream'
      path: '/api/admin/stream'
      fullPath: '/api/admin/stream'
      preLoaderRoute: typeof ApiAdminStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/axxonpay': {
      id: '/api/webhooks/axxonpay'
      path: '/api/webhooks/axxonpay'
      fullPath: '/api/webhooks/axxonpay'
      preLoaderRoute: typeof ApiWebhooksAxxonpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/beehive': {
      id: '/api/webhooks/beehive'
      path: '/api/webhooks/beehive'
      fullPath: '/api/webhooks/beehive'
      preLoaderRoute: typeof ApiWebhooksBeehiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  PoliticaDeEnvioRoute: PoliticaDeEnvioRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeReembolsoRoute: PoliticaDeReembolsoRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  AdminCartoesRoute: AdminCartoesRoute,
  AdminComprovantesRoute: AdminComprovantesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGatewaysRoute: AdminGatewaysRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminRastreioRoute: AdminRastreioRoute,
  AdminTiktokRoute: AdminTiktokRoute,
  AdminTrafegoRoute: AdminTrafegoRoute,
  CheckoutDadosRoute: CheckoutDadosRoute,
  CheckoutGarantiaRoute: CheckoutGarantiaRoute,
  CheckoutPixRoute: CheckoutPixRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
  CheckoutUpsellRoute: CheckoutUpsellRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminStreamRoute: ApiAdminStreamRoute,
  ApiWebhooksAxxonpayRoute: ApiWebhooksAxxonpayRoute,
  ApiWebhooksBeehiveRoute: ApiWebhooksBeehiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
